# Generated by Django 5.2.4 on 2025-08-15 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session_exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('sets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rest_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['training_session', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Training_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('goal', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='commentsection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='training_session',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='training_session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training_session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_client': True}, related_name='training_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='duration',
            field=models.DurationField(help_text='HH:MM:SS (e.g., 01:30:00 for 90 minutes)'),
        ),
        migrations.AddIndex(
            model_name='commentsection',
            index=models.Index(fields=['training_session', 'created_at'], name='core_commen_trainin_42833d_idx'),
        ),
        migrations.AddField(
            model_name='plan_assignment',
            name='client',
            field=models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session_exercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='core.exercise'),
        ),
        migrations.AddField(
            model_name='session_exercise',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='core.training_session'),
        ),
        migrations.AddField(
            model_name='training_plan',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan_assignment',
            name='training_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.training_plan'),
        ),
        migrations.AddField(
            model_name='training_session',
            name='training_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.training_plan'),
        ),
        migrations.AddIndex(
            model_name='training_session',
            index=models.Index(fields=['coach', 'date'], name='core_traini_coach_i_c22fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='session_exercise',
            index=models.Index(fields=['training_session', 'order'], name='core_sessio_trainin_9d6f4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='session_exercise',
            unique_together={('training_session', 'order')},
        ),
        migrations.AddIndex(
            model_name='training_plan',
            index=models.Index(fields=['coach', 'start_date'], name='core_traini_coach_i_9bf82d_idx'),
        ),
        migrations.AddIndex(
            model_name='plan_assignment',
            index=models.Index(fields=['training_plan', 'client'], name='core_plan_a_trainin_437abf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plan_assignment',
            unique_together={('training_plan', 'client')},
        ),
    ]
