# Generated by Django 5.2.4 on 2025-08-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercise_plan_assignment_session_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_session',
            name='activity_type',
            field=models.CharField(choices=[('Running', 'Running'), ('Cycling', 'Cycling'), ('Weightlifting', 'Weightlifting'), ('Swimming', 'Swimming'), ('Walking', 'Walking'), ('Yoga', 'Yoga')], default='Running', max_length=50),
        ),
        migrations.AddField(
            model_name='training_session',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training_session',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
